export interface Surah {
  index: number; // 0-113
  number: number; // 1-114
  name: string;
  arabic: string;
  verses: number;
  juz: number;
}

export const SURAHS: Surah[] = [
  { index: 0, number: 1, name: "Al-Fotiha", arabic: "الفاتحة", verses: 7, juz: 1 },
  { index: 1, number: 2, name: "Al-Baqara", arabic: "البقرة", verses: 286, juz: 1 },
  { index: 2, number: 3, name: "Ol Imron", arabic: "آل عمران", verses: 200, juz: 3 },
  { index: 3, number: 4, name: "An-Niso", arabic: "النساء", verses: 176, juz: 4 },
  { index: 4, number: 5, name: "Al-Moida", arabic: "المائدة", verses: 120, juz: 6 },
  { index: 5, number: 6, name: "Al-An'om", arabic: "الأنعام", verses: 165, juz: 7 },
  { index: 6, number: 7, name: "Al-A'rof", arabic: "الأعراف", verses: 206, juz: 8 },
  { index: 7, number: 8, name: "Al-Anfol", arabic: "الأنفال", verses: 75, juz: 9 },
  { index: 8, number: 9, name: "At-Tavba", arabic: "التوبة", verses: 129, juz: 10 },
  { index: 9, number: 10, name: "Yunus", arabic: "يونس", verses: 109, juz: 11 },
  { index: 10, number: 11, name: "Hud", arabic: "هود", verses: 123, juz: 11 },
  { index: 11, number: 12, name: "Yusuf", arabic: "يوسف", verses: 111, juz: 12 },
  { index: 12, number: 13, name: "Ar-Ra'd", arabic: "الرعد", verses: 43, juz: 13 },
  { index: 13, number: 14, name: "Ibrohim", arabic: "إبراهيم", verses: 52, juz: 13 },
  { index: 14, number: 15, name: "Al-Hijr", arabic: "الحجر", verses: 99, juz: 14 },
  { index: 15, number: 16, name: "An-Nahl", arabic: "النحل", verses: 128, juz: 14 },
  { index: 16, number: 17, name: "Al-Isro", arabic: "الإسراء", verses: 111, juz: 15 },
  { index: 17, number: 18, name: "Al-Kahf", arabic: "الكهف", verses: 110, juz: 15 },
  { index: 18, number: 19, name: "Maryam", arabic: "مريم", verses: 98, juz: 16 },
  { index: 19, number: 20, name: "Toha", arabic: "طه", verses: 135, juz: 16 },
  { index: 20, number: 21, name: "Al-Anbiyo", arabic: "الأنبياء", verses: 112, juz: 17 },
  { index: 21, number: 22, name: "Al-Hajj", arabic: "الحج", verses: 78, juz: 17 },
  { index: 22, number: 23, name: "Al-Mu'minun", arabic: "المؤمنون", verses: 118, juz: 18 },
  { index: 23, number: 24, name: "An-Nur", arabic: "النور", verses: 64, juz: 18 },
  { index: 24, number: 25, name: "Al-Furqon", arabic: "الفرقان", verses: 77, juz: 18 },
  { index: 25, number: 26, name: "Ash-Shuaro", arabic: "الشعراء", verses: 227, juz: 19 },
  { index: 26, number: 27, name: "An-Naml", arabic: "النمل", verses: 93, juz: 19 },
  { index: 27, number: 28, name: "Al-Qasas", arabic: "القصص", verses: 88, juz: 20 },
  { index: 28, number: 29, name: "Al-Ankabut", arabic: "العنكبوت", verses: 69, juz: 20 },
  { index: 29, number: 30, name: "Ar-Rum", arabic: "الروم", verses: 60, juz: 21 },
  { index: 30, number: 31, name: "Luqmon", arabic: "لقمان", verses: 34, juz: 21 },
  { index: 31, number: 32, name: "As-Sajda", arabic: "السجدة", verses: 30, juz: 21 },
  { index: 32, number: 33, name: "Al-Ahzob", arabic: "الأحزاب", verses: 73, juz: 21 },
  { index: 33, number: 34, name: "Sabo", arabic: "سبأ", verses: 54, juz: 22 },
  { index: 34, number: 35, name: "Fotir", arabic: "فاطر", verses: 45, juz: 22 },
  { index: 35, number: 36, name: "Yosin", arabic: "يس", verses: 83, juz: 22 },
  { index: 36, number: 37, name: "As-Soffot", arabic: "الصافات", verses: 182, juz: 23 },
  { index: 37, number: 38, name: "Sod", arabic: "ص", verses: 88, juz: 23 },
  { index: 38, number: 39, name: "Az-Zumar", arabic: "الزمر", verses: 75, juz: 23 },
  { index: 39, number: 40, name: "Ghofir", arabic: "غافر", verses: 85, juz: 24 },
  { index: 40, number: 41, name: "Fussilat", arabic: "فصلت", verses: 54, juz: 24 },
  { index: 41, number: 42, name: "Ash-Shuro", arabic: "الشورى", verses: 53, juz: 25 },
  { index: 42, number: 43, name: "Az-Zuxruf", arabic: "الزخرف", verses: 89, juz: 25 },
  { index: 43, number: 44, name: "Ad-Duxon", arabic: "الدخان", verses: 59, juz: 25 },
  { index: 44, number: 45, name: "Al-Josiya", arabic: "الجاثية", verses: 37, juz: 25 },
  { index: 45, number: 46, name: "Al-Ahqof", arabic: "الأحقاف", verses: 35, juz: 26 },
  { index: 46, number: 47, name: "Muhammad", arabic: "محمد", verses: 38, juz: 26 },
  { index: 47, number: 48, name: "Al-Fath", arabic: "الفتح", verses: 29, juz: 26 },
  { index: 48, number: 49, name: "Al-Hujurot", arabic: "الحجرات", verses: 18, juz: 26 },
  { index: 49, number: 50, name: "Qof", arabic: "ق", verses: 45, juz: 26 },
  { index: 50, number: 51, name: "Az-Zoriyot", arabic: "الذاريات", verses: 60, juz: 26 },
  { index: 51, number: 52, name: "At-Tur", arabic: "الطور", verses: 49, juz: 27 },
  { index: 52, number: 53, name: "An-Najm", arabic: "النجم", verses: 62, juz: 27 },
  { index: 53, number: 54, name: "Al-Qamar", arabic: "القمر", verses: 55, juz: 27 },
  { index: 54, number: 55, name: "Ar-Rohmon", arabic: "الرحمن", verses: 78, juz: 27 },
  { index: 55, number: 56, name: "Al-Voqia", arabic: "الواقعة", verses: 96, juz: 27 },
  { index: 56, number: 57, name: "Al-Hadid", arabic: "الحديد", verses: 29, juz: 27 },
  { index: 57, number: 58, name: "Al-Mujodila", arabic: "المجادلة", verses: 22, juz: 28 },
  { index: 58, number: 59, name: "Al-Hashr", arabic: "الحشر", verses: 24, juz: 28 },
  { index: 59, number: 60, name: "Al-Mumtahana", arabic: "الممتحنة", verses: 13, juz: 28 },
  { index: 60, number: 61, name: "As-Saf", arabic: "الصف", verses: 14, juz: 28 },
  { index: 61, number: 62, name: "Al-Jumu'a", arabic: "الجمعة", verses: 11, juz: 28 },
  { index: 62, number: 63, name: "Al-Munofiqun", arabic: "المنافقون", verses: 11, juz: 28 },
  { index: 63, number: 64, name: "At-Taghabun", arabic: "التغابن", verses: 18, juz: 28 },
  { index: 64, number: 65, name: "At-Taloq", arabic: "الطلاق", verses: 12, juz: 28 },
  { index: 65, number: 66, name: "At-Tahrim", arabic: "التحريم", verses: 12, juz: 28 },
  { index: 66, number: 67, name: "Al-Mulk", arabic: "الملك", verses: 30, juz: 29 },
  { index: 67, number: 68, name: "Al-Qalam", arabic: "القلم", verses: 52, juz: 29 },
  { index: 68, number: 69, name: "Al-Haqqa", arabic: "الحاقة", verses: 52, juz: 29 },
  { index: 69, number: 70, name: "Al-Ma'orij", arabic: "المعارج", verses: 44, juz: 29 },
  { index: 70, number: 71, name: "Nuh", arabic: "نوح", verses: 28, juz: 29 },
  { index: 71, number: 72, name: "Al-Jinn", arabic: "الجن", verses: 28, juz: 29 },
  { index: 72, number: 73, name: "Al-Muzzammil", arabic: "المزمل", verses: 20, juz: 29 },
  { index: 73, number: 74, name: "Al-Muddassir", arabic: "المدثر", verses: 56, juz: 29 },
  { index: 74, number: 75, name: "Al-Qiyoma", arabic: "القيامة", verses: 40, juz: 29 },
  { index: 75, number: 76, name: "Al-Inson", arabic: "الإنسان", verses: 31, juz: 29 },
  { index: 76, number: 77, name: "Al-Mursalot", arabic: "المرسلات", verses: 50, juz: 29 },
  { index: 77, number: 78, name: "An-Naba", arabic: "النبأ", verses: 40, juz: 30 },
  { index: 78, number: 79, name: "An-Nozi'ot", arabic: "النازعات", verses: 46, juz: 30 },
  { index: 79, number: 80, name: "Abasa", arabic: "عبس", verses: 42, juz: 30 },
  { index: 80, number: 81, name: "At-Takwir", arabic: "التكوير", verses: 29, juz: 30 },
  { index: 81, number: 82, name: "Al-Infitor", arabic: "الانفطار", verses: 19, juz: 30 },
  { index: 82, number: 83, name: "Al-Mutaffifin", arabic: "المطففين", verses: 36, juz: 30 },
  { index: 83, number: 84, name: "Al-Inshiqoq", arabic: "الانشقاق", verses: 25, juz: 30 },
  { index: 84, number: 85, name: "Al-Buruj", arabic: "البروج", verses: 22, juz: 30 },
  { index: 85, number: 86, name: "At-Toriq", arabic: "الطارق", verses: 17, juz: 30 },
  { index: 86, number: 87, name: "Al-A'lo", arabic: "الأعلى", verses: 19, juz: 30 },
  { index: 87, number: 88, name: "Al-Ghoshiya", arabic: "الغاشية", verses: 26, juz: 30 },
  { index: 88, number: 89, name: "Al-Fajr", arabic: "الفجر", verses: 30, juz: 30 },
  { index: 89, number: 90, name: "Al-Balad", arabic: "البلد", verses: 20, juz: 30 },
  { index: 90, number: 91, name: "Ash-Shams", arabic: "الشمس", verses: 15, juz: 30 },
  { index: 91, number: 92, name: "Al-Layl", arabic: "الليل", verses: 21, juz: 30 },
  { index: 92, number: 93, name: "Ad-Duho", arabic: "الضحى", verses: 11, juz: 30 },
  { index: 93, number: 94, name: "Al-Inshiroh", arabic: "الشرح", verses: 8, juz: 30 },
  { index: 94, number: 95, name: "At-Tin", arabic: "التين", verses: 8, juz: 30 },
  { index: 95, number: 96, name: "Al-Aloq", arabic: "العلق", verses: 19, juz: 30 },
  { index: 96, number: 97, name: "Al-Qadr", arabic: "القدر", verses: 5, juz: 30 },
  { index: 97, number: 98, name: "Al-Bayyina", arabic: "البينة", verses: 8, juz: 30 },
  { index: 98, number: 99, name: "Az-Zalzala", arabic: "الزلزلة", verses: 8, juz: 30 },
  { index: 99, number: 100, name: "Al-Odiyot", arabic: "العاديات", verses: 11, juz: 30 },
  { index: 100, number: 101, name: "Al-Qori'a", arabic: "القارعة", verses: 11, juz: 30 },
  { index: 101, number: 102, name: "At-Takosur", arabic: "التكاثر", verses: 8, juz: 30 },
  { index: 102, number: 103, name: "Al-Asr", arabic: "العصر", verses: 3, juz: 30 },
  { index: 103, number: 104, name: "Al-Humaza", arabic: "الهمزة", verses: 9, juz: 30 },
  { index: 104, number: 105, name: "Al-Fil", arabic: "الفيل", verses: 5, juz: 30 },
  { index: 105, number: 106, name: "Quraysh", arabic: "قريش", verses: 4, juz: 30 },
  { index: 106, number: 107, name: "Al-Mo'un", arabic: "الماعون", verses: 7, juz: 30 },
  { index: 107, number: 108, name: "Al-Kavsar", arabic: "الكوثر", verses: 3, juz: 30 },
  { index: 108, number: 109, name: "Al-Kofirun", arabic: "الكافرون", verses: 6, juz: 30 },
  { index: 109, number: 110, name: "An-Nasr", arabic: "النصر", verses: 3, juz: 30 },
  { index: 110, number: 111, name: "Al-Masad", arabic: "المسد", verses: 5, juz: 30 },
  { index: 111, number: 112, name: "Al-Ixlos", arabic: "الإخلاص", verses: 4, juz: 30 },
  { index: 112, number: 113, name: "Al-Falaq", arabic: "الفلق", verses: 5, juz: 30 },
  { index: 113, number: 114, name: "An-Nos", arabic: "الناس", verses: 6, juz: 30 },
];
